### ISSUE TITLE
Whitelist "dinput8.dll" as "native, then built-in" by default in every new Proton prefix

### ISSUE THREAD

**Issue by Tiagoquix** [Open-Wine-Components/umu-protonfixes#123]
This could be considered as a request for Proton-GE.
Sorry if this is not the right place to request it, but it seems to be the most appropriate one.

See https://github.com/ValveSoftware/Proton/issues/7974 for rationale.

**Comment by Root-Core** [comment]
I'm not sure if this is in the scope of this project or even Proton-GE. If there is something that needs a fix, the fix will already set the override. If there is nothing to fix, we will not apply a fix. The `protonfixes` are meant to be a stopgap and will (should) be removed once upstream fixes the games / issues.

The Ultimate-ASI-Loader also isn't limited to `dinput8.dll` and it might add some yet unknown incompatibilities or problems, if the game includes a `dinput8.dll` already which does not work well with wine.

-----------------

You could however make this work for your local machine.
Just create a file with following path:

>~/.config/protonfixes/localfixes/default.py

```python
"""Default file for all games, with all protonfix versions"""

from protonfixes import util

def main() -> None:
    """Global defaults"""
    util.winedll_override('dinput8', 'n,b')
```

This should work for your use case and be run by default for every game.
Keep in mind that it only works, if `protontricks` is actually executed. For example with GE-Proton and UMU-Proton.

You can also add or modify game specific fixes in this folder.. we will add some documentation about this in the future.
CC #122
