### ISSUE TITLE
CPU limits are now in Valve's Proton

### ISSUE THREAD

**Issue by Root-Core** [Open-Wine-Components/umu-protonfixes#53]
Proton added fixes for high CPU core count related issues. We might remove some of our fixes.

https://github.com/ValveSoftware/Proton/blob/3ce5d95185904545246223ff26dcaa82362cb10f/proton#L1148-L1159

I would research this further, but my system's main SSD crapped it's pants and I can't replace it right now.

**Comment by GloriousEggroll** [comment]
closing as rika already merged a fix regarding this
