### ISSUE TITLE
Making Protonfix Scripts work on Non-Steam games via GE-Proton?

### ISSUE THREAD

**Issue by CreeperofDoom** [Open-Wine-Components/umu-protonfixes#61]
I recently submitted a fix for many Titles that aimed to resolve WMP9 Video Playback. Is there any way to make this apply to a Non-Steam title as well? A certain area of it will crash and i cant progress unless the video plays properly. Using Protontricks will make it black screen instead and force me to exit via the Steam Overlay

Steam Deck with GE-Proton 9-4

**Comment by marianoag** [comment]
If the game is also on Steam you can make a protonfix for Steam and then with Steam's appid a .py file in for the Store with only the relative path to the Steam one.

If it's not on Steam then the filename depends on the store, check  https://github.com/Open-Wine-Components/umu-database for instructions.
